# Big Data Skill Up Training Notebook

<u>Based on [Samy Baladram's Lesson](https://sites.google.com/tohoku.ac.jp/gpds-course/courses/skill-up-training), International Liasion Office-GSIS-Tohoku University.</u>

Last updated by [Shinil](mailto:baisy1999@outlook.com):21-10-20

## 1.1 Variables 

print() function

In [1]:
print ( "Research Student life in Tohoku University!")

Research Student life in Tohoku University!


In [3]:
my_goal = "To gain enough knowledge."
print( my_goal)

To gain enough knowledge.


In [4]:
my_degree = "Bachelor of Science"
print( my_degree )

Bachelor of Science


In [5]:
#Write your annotation after #
print( my_goal )
print( my_degree )

To gain enough knowledge.
Bachelor of Science


## 1.2 Strings

In [6]:
print( 'My research student life begins in:', '\n', 'Tohoku University')

My research student life begins in: 
 Tohoku University


In [7]:
city_tohoku = 'Miyagi'
print( 'Tohoku Uni. is located at:', city_tohoku)

Tohoku Uni. is located at: Miyagi


In [8]:
print(str.upper(city_tohoku), str.capitalize(city_tohoku), str.lower(city_tohoku) )

MIYAGI Miyagi miyagi


In [9]:
#You may use \, \t, \n inside ""
print('City: Miyagi \tKen:Aoba\n Tohoku University')

City: Miyagi 	Ken:Aoba
 Tohoku University


## 1.3 Numbers

In [11]:
#use + - * / ** as the math operators
#using string format like commas as thousands
a = 15000
print(f'the number is {a:.2f}')
print(f'the number is {a:,d}')

the number is 15000.00
the number is 15,000


In [13]:
#use func type(), int(), float(), str() to change the data types
#keep the balance of using spaces between operators
score_1 = 95
score_2 = 90
score_3 = 85
score_sum = score_1 + score_2 + score_3 
score_ave = score_sum/3  

print(f'score sum: {score_sum} and average score: {score_ave:.0f}')

score sum: 270 and average score: 90


## 1.4 Lists

A list is a collection of items with its own order. Use [] to indicate a list, and each element in the list is separated by commas.

In [15]:
city = ['Tokyo', 'Beijing', 'Seoul']
university = ['UoT', 'PKU', 'SNU']

print(city)
print(university)

['Tokyo', 'Beijing', 'Seoul']
['UoT', 'PKU', 'SNU']


Use the index of the element to access the element in the list, start from item.[0]

In [16]:
print(city[1])

Beijing


To get the last element in the list, use the negative index like -1

In [17]:
print(university[-1])

SNU


Use the '=' to change the elements in the list

In [18]:
university[1] = 'TSU'
print(university[1])

TSU


## 1.5 List Method

To add elements in the list, use append(item) to add items to the end of the list, use insert(pos, item) to add items to the index pos in the list.

In [21]:
city = ['Tokyo', 'Beijing', 'Seoul']
city.append('Los Angles')
print(f'New citylist: {city}')
city.insert(1,'Tianjin')
print(f'Second version of the list {city}')

New citylist: ['Tokyo', 'Beijing', 'Seoul', 'Los Angles']
Second version of the list ['Tokyo', 'Tianjin', 'Beijing', 'Seoul', 'Los Angles']


To delete elements of a list, use pop(pos) to delete with index pos (default is -1), or use remove(itemname) to delete the element with its name.

In [25]:
city = ['Tokyo', 'Beijing', 'Seoul','Koyto']

city.pop(1)
print(city)

city.pop(-1)
print(city)

city.remove('Seoul')
print(city)

['Tokyo', 'Seoul', 'Koyto']
['Tokyo', 'Seoul']
['Tokyo']


Use sort() to sort the list or use reverse() to reverse the order of the list.

In [26]:
city = ['Tokyo', 'Beijing', 'Seoul','Koyto']

#here use the sort() to sort the list alphabetically
city.sort()
print(city)

['Beijing', 'Koyto', 'Seoul', 'Tokyo']


To combine two lists by list1.extend(list2) and to make a seperate list use operator + insted.

In [28]:
city = ['Tokyo', 'Beijing', 'Seoul','Koyto']
university = ['UoT', 'PKU', 'SNU']

city_and_uni = city + university
print(city_and_uni)

city.extend(university)
print(city)

['Tokyo', 'Beijing', 'Seoul', 'Koyto', 'UoT', 'PKU', 'SNU']
['Tokyo', 'Beijing', 'Seoul', 'Koyto', 'UoT', 'PKU', 'SNU']


Use index(itemname) to get the index of the first element with the name itemname. Use count(itemname) to get the number of elements with the name itemname.

In [29]:
city = ['Tokyo', 'Beijing','Beijing', 'Seoul','Koyto']

print(city.index('Beijing'))
print(city.count('Beijing'))

1
2


## 1.6 Slice Operator

Use \[start : end \] to get the slice of the list and be careful the end index is exclusice while the start index is inclusive. Omitting index slice operartor is allowed. 

In [30]:
city = ['Tokyo', 'Beijing', 'Seoul','Koyto']

print(city[1:4])
print(city[:3])
print(city[-2:])

['Beijing', 'Seoul', 'Koyto']
['Tokyo', 'Beijing', 'Seoul']
['Seoul', 'Koyto']


Use \[start : stop : steps \] to slice a list with steps.

In [31]:
city = ['Tokyo', 'Beijing', 'Seoul','Koyto']
print(city[1::2])

['Beijing', 'Koyto']


To copy a list, use a slice of original list with both indexes omitted or use list.copy()

In [34]:
city = ['Tokyo', 'Beijing', 'Seoul','Koyto']

city_1 = city[:]
city_2 = city.copy()

city_1.append('Tianjin')
city_2.append('Shanghai')

print(city_1[-1])
print(city_2[-1])

Tianjin
Shanghai


## 2.1 Loop

The for loop takes an element from the list one by one to the process.

In [2]:
city = ['Tokyo', 'Beijing', 'Seoul','Koyto']

for city in city:
    print(f'City: {city} \n')

City: Tokyo 

City: Beijing 

City: Seoul 

City: Koyto 



In [3]:
names = ['Andy', 'Brad', 'Cody']
grades = [65, 70, 85]
numbers = [0, 1, 2]

for num in numbers:
  print(f'Name : {names[num]}')
  print(f'Grade : {grades[num]}\n')
print('-------------')

Name : Andy
Grade : 65

Name : Brad
Grade : 70

Name : Cody
Grade : 85

-------------


Use the assignment operator to improve.
+=, -=, *=, /=

In [5]:
grades_andy = [65, 75, 80, 85]

total = 0
for grade in grades_andy:
  total += grade
print(total)

305


## 2.2 List Comprehension

Use range() to generate list of numbers
range(end) (same as) range(0,end) 
which gives a sequence of numbers from 0 to end-1.

Similarly, range(start, end) gives numbers from start to end-1.

Tip: range() does not return to a list, you can use list() to turn it into a list.

In [1]:
names = ['Andy', 'Brad', 'Cody']
test_score = [13, 14, 17]

grades = []
for num in range(3):
  grades.append(test_score[num] * 5)
  
print(grades)

[65, 70, 85]


A list comprehension allows to generate same list in one line of code.

In [2]:
names = ['Andy', 'Brad', 'Cody']
test_score = [13, 14, 17]

grades = [score * 5 for score in test_score]
  
print(grades)

[65, 70, 85]


## 2.3 Boolean Operators

Boolean value: True, False

==, !=, <, >, <=, >= can be used for logic operations and it will result in a boolean value.

In [3]:
logic_1 = 'Andy' == 'Brad'
print(logic_1, type(logic_1))

logic_2 = 65 <= 65
print(logic_2)

logic_3 = (5*13) > (5*14)
print(logic_3)

logic_4 = 'andy' != 'Andy'
print(logic_4)

False <class 'bool'>
True
False
True


In some specific conditions it is better to use 'and, or, not' to compare different boolean conditons.

In [4]:
mark_1, mark_2 = 65, 75

logic_1 = (mark_1 > 65) and (mark_2 > 65)
logic_1 = (mark_1 > 65)  &  (mark_2 > 65)
print(logic_1)

logic_2 = (mark_1 > 80) or (mark_2 > 80)
logic_2 = (mark_1 > 80)  | (mark_2 > 80)
print(logic_2)

logic_3 = not (mark_1 <= mark_2)
logic_3 = bool(~(mark_1 <= mark_2))
print(logic_3)

False
False
True


To check whether a value appear or not in a list, you can use 'in' operator and 'not' to check if the item is not in a list.

In [5]:
names = ['Andy', 'Brad', 'Cody']

logic_1 = 'Cody' in names
print(logic_1)

logic_2 = 'Drew' not in names
print(logic_2)

True
True


## 2.4 if Statement

if Statement can be used as follows

In [11]:
mark = 65

if mark > 60:
  print("Passed")

mark_2 = 59
if mark_2 < 60:
    print('Failed')

Passed
Failed


Use if-else to make conditional satements.

In [12]:
mark = 65

if mark > 60:
  print("Passed")
else:
  print("Failed")

Passed


Use if-else-else to chain conditions. Use elif when it is needed.

In [13]:
mark = 65

is_grade_A = 85 <= mark <= 100
is_grade_B = 70 <= mark < 85
is_grade_C = 60 <= mark < 70

print(f'Mark : {mark}')
if is_grade_A:
  print("Grade: A")
elif is_grade_B:
  print("Grade: B")
elif is_grade_C:
  print("Grade: C")
else:
  print("Grade: F")

Mark : 65
Grade: C


## 2.5 Looping if Statement

Combining if and for

In [14]:
names = ['Andy', 'Brad', 'Cody']
marks = [65, 70, 55]

names_pass, names_fail = [], []

for i in range(3):
  if marks[i] > 60:
    names_pass.append(names[i])
  else:
    names_fail.append(names[i])

print(f"Passing Students:")
print(names_pass)

print("\nFailing Students:")
print(names_fail)

Passing Students:
['Andy', 'Brad']

Failing Students:
['Cody']


Using if with list comprehension.

In [15]:
names = ['Andy', 'Brad', 'Cody']
marks = [65, 70, 55]

names_pass = [names[i] for i in range(3) 
              if marks[i] > 60]
names_fail = [names[i] for i in range(3) 
              if marks[i] <= 60]

print("Passing Students:")
print(names_pass)

print("\nFailing Students:")
print(names_fail)

#it is a different way with the method above

Passing Students:
['Andy', 'Brad']

Failing Students:
['Cody']


Using if-else with list comprehension.

In [16]:
names = ['Andy', 'Brad', 'Cody']
marks = [65, 70, 55]

status = ['Passed' if mark > 60 else
          'Failed' for mark in marks]
#in this case the for-loop part has to be written after the else part

print(names)
print(status)

['Andy', 'Brad', 'Cody']
['Passed', 'Passed', 'Failed']


Using multiple if-else in list comprehension.

In [17]:
names = ['Andy', 'Brad', 'Cody']
marks = [65, 70, 55]

status = ['Passed' if mark > 60 else
          'Failed' for mark in marks]

grades = ['A' if 85 <= mark <= 100 else
          'B' if 70 <= mark < 85 else
          'C' if 60 <= mark < 70 else
          'F' for mark in marks]
          
print(names)
print(status)
print(grades)

['Andy', 'Brad', 'Cody']
['Passed', 'Passed', 'Failed']
['C', 'B', 'F']


## 3.1 Tuples

Tuples are used to store multiple items in a single variable. It can be written with () or separating a sequence with commas.

In [1]:
stats = ('name', 'mark', 'grade')
print(stats)

stats = 'name', 'mark', 'grade'
print(stats)

('name', 'mark', 'grade')
('name', 'mark', 'grade')


Like list, use \[index\] to access the items in a tuple. Also you can use index() and count(). Attention, the elements inside the tuple can not be modified.

In [4]:
stats = ('name', 'mark', 'grade')

print(stats[0])
print(stats[:2])
print(stats[-3:-2])

print(stats.index('mark'))
print(stats.count('grade'))

name
('name', 'mark')
('name',)
1
1


You can use len(), index(), count() with a tuple.

In [5]:
stats = ('name', 'mark', 'grade')

print(len(stats))

3


Generator expression is similar to list comprehension. The resulting object is called a generator. You can not print generator directly withou converting it to list/tuple first. To convert this into a tuple, you can use tuple().

In [6]:
stats = ('name', 'mark', 'grade')

stat_gen = (stat.title() for stat in stats)

print(stat_gen)
print(tuple(stat_gen))

<generator object <genexpr> at 0x11703a5f0>
('Name', 'Mark', 'Grade')


Again, the items in a tuple can not be modified, like append(), insert(), remove(), pop(), sort() are not usable.

## 3.2 Sets

A set is used to store multiple items in a single variabe. It is written with {}. But a set does not have order and index, and it can not have two items with the same value.

In [7]:
verbs = {'read', 'write', 'listen', 
        'speak', 'read', 'read'}

print(verbs)

{'speak', 'read', 'listen', 'write'}


To add items to a set, you can use add(item) and update(iterable).

In [8]:
verbs = {'read', 'write', 'listen'}

verbs.add('eat')

new_verbs = ['buy', 'sell']

verbs.update(new_verbs)

print(verbs)

{'buy', 'sell', 'write', 'read', 'listen', 'eat'}


To remove an item in a set, you can use remove(item) and pop(), where pop() removes the last item in a set. Since there is no order in sets, so you will not know which item gets removed.

In [10]:
verbs = {'read', 'write', 'listen',
         'eat', 'buy', 'sell'}

verbs.remove('write')
verbs.pop()

popped_item = verbs.pop()

print(verbs)
print(popped_item)

{'sell', 'read', 'listen'}
buy


There are some methods that can be applied only to sets.

difference(set) returns a set containing the difference between two or more sets.

symmetric_difference(set) returns a set with the symmetric difference of two sets.

intersection(set) returns a set that is the intersection of two other sets.

union(set) returns a set containing the union of sets.

In [11]:
set_1 = {1, 2, 3, 4, 5}
set_2 = {3, 4, 5, 6 ,7}

diffr_12 = set_1.difference(set_2)
print(f'Difference:\t{diffr_12}')

symdf_12 = set_1.symmetric_difference(set_2)
print(f'Sym Difference:\t{symdf_12}')

insec_12 = set_1.intersection(set_2)
print(f'Intersection:\t{insec_12}')

union_12 = set_1.union(set_2)
print(f'Union: {union_12}')

Difference:	{1, 2}
Sym Difference:	{1, 2, 6, 7}
Intersection:	{3, 4, 5}
Union: {1, 2, 3, 4, 5, 6, 7}


Since sets cannot have multiple occurrences of the same element, they are useful to remove duplicate values from a list/tuple and to perform operations like unions and intersections.You can easily convert a list or tuple to a set using set() and you can check its length using len(), just like in list and tuple.

In [12]:
student_list = ['Andy', 'Andy', 'Brad',
                'Cody', 'Cody', 'Eddy']

student_set = set(student_list)
print(student_set)
print(f"Number of Student: {len(student_set)}")

{'Andy', 'Brad', 'Cody', 'Eddy'}
Number of Student: 4


## 3.3 Dictionary

A dictionary is used to store data values in key:value pairs.They are written with curly brackes { } and have keys and values, separated by colon :.

In [13]:
student_1 = {'name':'Andy', 'mark': 65, 'grade':'C'}

print(student_1)

{'name': 'Andy', 'mark': 65, 'grade': 'C'}


To access the items of a dictionary, you can use key name inside the square bracket.

Also you can use get(key) to access.

In [14]:
student_1 = {'name':'Andy', 'mark': 65, 'grade':'C'}

print(student_1['name'])
print(student_1.get('grade'))

Andy
C


In general, keys can not be changed. You can change the values of a specific item be referring to its key name.

update(dict) can also upate the dictionary. The arguement must be a dictionary.

Those two methods can also be used to add new keys:values pair into a dictionary.

In [15]:
student_1 = {'name':'Andy', 'mark': 65, 'grade':'C'}

student_1['grade'] = 'B'
student_1.update({'mark': 75})
print(student_1)

student_1['class'] = 'math'
student_1.update({'year': 2020})
print(student_1)

{'name': 'Andy', 'mark': 75, 'grade': 'B'}
{'name': 'Andy', 'mark': 75, 'grade': 'B', 'class': 'math', 'year': 2020}


pop() removes the element with the specified key. The value of the removed item is the return value of the pop() method.

In [16]:
student_1 = {'name':'Andy', 'mark': 75, 'grade':'B'}

popped_grade = student_1.pop('grade')
print(student_1)
print(popped_grade)

{'name': 'Andy', 'mark': 75}
B


<u>In summary, be careful on the difference among tuples, sets and dictionaries.</u>

## 3.4 Loop in dictionaries

To get all the keys, values, or all items, you can use the following methods:

keys() returns a list of all the keys in the dictionary.

values() returns a list of all the values in the dictionary.

items() returns each item in a dictionary as tuples in a list.

In [1]:
student_1 = {'name':'Andy', 'mark': 75, 'grade':'B'}

print(student_1.keys())
print(student_1.values())
print(student_1.items())

print(list(student_1.keys())) # <- convert to a list

dict_keys(['name', 'mark', 'grade'])
dict_values(['Andy', 75, 'B'])
dict_items([('name', 'Andy'), ('mark', 75), ('grade', 'B')])
['name', 'mark', 'grade']


Looping through a dictionary with keys(), values(), items()

In [18]:
stud_1_data = {'name':'Andy', 'mark':75, 'grade':'B'}

stats  = (stat for stat in stud_1_data.keys())

stud_1 = (info for info in stud_1_data.values())

stud_1_bio = [(stat,info) 
              for stat, info in stud_1_data.items()]

print(tuple(stats))
print(list(stud_1))
print(stud_1_bio)

('name', 'mark', 'grade')
['Andy', 75, 'B']
[('name', 'Andy'), ('mark', 75), ('grade', 'B')]


To form a dictionary from two tuples/lists, you can start by making an empty dictionary first then add the items in a for loop using a simple index assignment or update().

In [19]:
stats = ('name', 'mark', 'grade')
stud_1 = ['Andy', 75, 'B']

stud_1_data = {}
for i in range(len(stats)):
  stud_1_data.update({stats[i]:stud_1[i]})

print(stud_1_data)

{'name': 'Andy', 'mark': 75, 'grade': 'B'}


Dictionary comprehension can be applied as follows.

In [20]:
stats = ('name', 'mark', 'grade')
stud_1 = ['Andy', 75, 'B']

stud_1_data = {stats[i]:stud_1[i] 
               for i in range(len(stats))}

print(stud_1_data)

{'name': 'Andy', 'mark': 75, 'grade': 'B'}


## 3.5 Zip and Enumerate

The zip(iter1,iter2,...) function takes multiple iterables (such as list, tuple, dictionary, etc.), joins them in a tuple, and returns it. 

Since it cannot be printed directly, the for loop can be used here. 

In [21]:
stats = ('name', 'mark', 'grade')
stud_1 = ['Andy', 75, 'B']

stud_1_zip = zip(stats, stud_1)

for stat, info in zip(stats, stud_1):
  print(f"{stat.title()}\t: {info}")

Name	: Andy
Mark	: 75
Grade	: B


Since the zip object is essentially a collection of 2-tuples, it can be easily converted to dictionary using dict().

In [22]:
stats = ('name', 'mark', 'grade')
stud_1 = ['Andy', 75, 'B']

stud_1_zip = zip(stats, stud_1)
stud_1_data= dict(stud_1_zip)

print(stud_1_data)

{'name': 'Andy', 'mark': 75, 'grade': 'B'}


enumerate(container, start=num) gives an iterable (like zip) that contain the index and the items in the container.

It can be combined with the zip() method as well. Just like zip, it cannot be printed.

In [23]:
stats = ('name', 'mark', 'grade')
stud_1 = ['Andy', 75, 'B']
stud_2 = ['Brad', 85, 'A']

stud_1_data = dict(zip(stats, stud_1))
stud_2_data = dict(zip(stats, stud_2))

stud_list = [stud_1_data, stud_2_data]

stud_index = enumerate(stud_list, start=1)

stud_dict = {f'ID{index}': info
             for index, info in stud_index}
               
print(stud_dict)

{'ID1': {'name': 'Andy', 'mark': 75, 'grade': 'B'}, 'ID2': {'name': 'Brad', 'mark': 85, 'grade': 'A'}}


To separate the elements of each tuple into independent sequences, you can use zip() along with the unpacking operator *.

In [24]:
stud_dict = (('ID1', {'name': 'Andy', 'mark': 75}),
             ('ID2', {'name': 'Brad', 'mark': 85}))
       
stud_id, stud_info = zip(*stud_dict)
print(stud_id)
print(stud_info)

('ID1', 'ID2')
({'name': 'Andy', 'mark': 75}, {'name': 'Brad', 'mark': 85})


Notice: Both zip and enumerate are exhaust iterators--meaning after you unpack it once, it will become exhausted and no longer usable.

So, you need to explicitly convert the iterator into a list/tuple if you want to unpack it multiple times. Enclosed the zip() with tuple() to resolve the error.

## 4.1 Functions

A function is defined using the def keyword. Similar to for and if, the indented lines after that will be part of that function.

In [4]:
name = "Shinil"

def print_name():
  print(f"Name: {name}")

print_name()

Name: Shinil


Arguments are added after the function name, inside the parentheses. You can add as many arguments as you want, just separate them with a comma.

In [5]:
def print_name(name):
  print(f"Name: {name}")

print_name("Shinil")
print_name("Shinitsu")

Name: Shinil
Name: Shinitsu


In [6]:
def print_stats(name, sex, uni):
  print(f"Name : {name}")
  print(f"Sex : {sex}")
  print(f"University: {uni}\n")

print_stats("Shenyi", 'Male', 'Nankai')
print_stats("Shinil", 'Male', 'Tohoku')

Name : Shenyi
Sex : Male
University: Nankai

Name : Shinil
Sex : Male
University: Tohoku



Some data or parameters might be incomplete. Adding a default value to a function can help with this. If we call the function without argument, it will use the default value.

In [8]:
def print_stats(name='Please enter your info', mark='?', grade='?'):
  print(f"Name : {name}")
  print(f"Mark : {mark}")
  print(f"Grade: {grade}\n")

print_stats("Shenyi", 75, 'B+')
print_stats("Shinil")
print_stats()

Name : Shenyi
Mark : 75
Grade: B+

Name : Shinil
Mark : ?
Grade: ?

Name : Please enter your info
Mark : ?
Grade: ?



You can send any data types of argument to a function (string, number, list, dictionary, etc.), and it will be treated as the same data type inside the function.

In [9]:
stu_1 = ["Shenyi", 75, 'B+']
stu_2 = ["Shinitsu", 85, 'A-']

def print_stats(stu_stat):
  print(f"Name : {stu_stat[0]}")
  print(f"Mark : {stu_stat[1]}")
  print(f"Grade: {stu_stat[2]}\n")

print_stats(stu_1)
print_stats(stu_2)

Name : Shenyi
Mark : 75
Grade: B+

Name : Shinitsu
Mark : 85
Grade: A-



## 4.2 Lambda Functions

To make a function return a value, use the return statement. Having a return value means you can save the result of the function into a  variable.

In [13]:
def is_pass(mark):
  if mark >= 60:
    result = "Pass"
  else:
    result = "Fail"
  return result

mark_1  = 60
result_1 = is_pass(mark_1)
print(f"Mark  : {mark_1}")
print(f"Result: {result_1}")

Mark  : 60
Result: Pass


A <u>lambda function</u> is a small anonymous function.

It can only have one expression and will also return that one expression. In this example, we will use a generator expression.

In [14]:
is_pass = lambda mark : ("Pass" if mark >= 60 else "Fail")

mark_1  = 60
result_1 = is_pass(mark_1)
print(f"Mark  : {mark_1}")
print(f"Result: {result_1}")

Mark  : 60
Result: Pass


While you can add a generator expression, lambda functions are commonly used for simple calculation.

It can accept multiple arguments as well.

In [17]:
ave_mark = lambda m_1, m_2 : ((m_1 + m_2) / 2)
is_pass = lambda mark : ("Pass" if mark >= 60 else "Fail")

mark_1 = 60
mark_2 = 65
ave = ave_mark(mark_1, mark_2)
result_1 = is_pass(ave)

print(f"Mark 1  : {mark_1}")
print(f"Mark 2  : {mark_2}")
print(f"Average mark: {ave}")
print(f"Result  : {result_1}")

Mark 1  : 60
Mark 2  : 65
Average mark: 62.5
Result  : Pass


Lambda functions are best for use for smaller functions (only one line of code). If a function is more than one line, it is recommended to use def instead.

In [18]:
ave_mark = lambda m_1, m_2 : ((m_1 + m_2) / 2)
is_pass = lambda mark : ("Pass" if mark >= 60 else "Fail")

names = ["Shenyi", "Raymond", "Haku"]

marks_1 = [60, 85, 70]
marks_2 = [65, 65, 60]
marks_ave = [ave_mark(m_1, m_2) 
            for m_1, m_2 in zip(marks_1, marks_2)]
results = [is_pass(ave) for ave in marks_ave]

def stats(name='Please input your information.', mark_1="?", mark_2="?", result="?"):
  message = f"Name      : {name}\n\
  Mark 1  : {mark_1}\n\
  Mark 2  : {mark_2}\n\
  Result  : {result}\n"
  return message
  
stud_data = zip(names, marks_1, marks_2, results)

for name, mark_1, mark_2, result in stud_data:
  print(stats(name, mark_1, mark_2, result))

Name      : Shenyi
  Mark 1  : 60
  Mark 2  : 65
  Result  : Pass

Name      : Raymond
  Mark 1  : 85
  Mark 2  : 65
  Result  : Pass

Name      : Haku
  Mark 1  : 70
  Mark 2  : 60
  Result  : Pass



## 4.3 Exceptions

When an error occurs, it can be handled by using try and except statement.

In [20]:
grades = ['65', '75', '65', 'miss']

def attempt_int(x):
  try:
    return int(x)
  except:
    return x

grades_int = [attempt_int(grade) 
              for grade in grades]

print(grades_int)

[65, 75, 65, 'miss']


When a data that we have is not clean, try and except can be really useful, especially when multiple lists exist. We can assign the value if an error occurred.

In [26]:
names = ['Andy', "Brad", "Cody"]
marks_1 = ['65', '75',  '65s']
marks_2 = ['65', '8 5',  '60']

def attempt_ave(x1, x2):
  try:
    return (int(x1) + int(x2)) / 2
  except:
    return "?"
    
marks_int = [attempt_ave(m1, m2) 
             for m1, m2 in zip(marks_1, marks_2)]

print(f"Name: {names}")
print(f"Marks 1: {marks_1}")
print(f"Marks 2: {marks_2}")
print(f"Average: {marks_int}")

Name: ['Andy', 'Brad', 'Cody']
Marks 1: ['65', '75', '65s']
Marks 2: ['65', '8 5', '60']
Average: [65.0, '?', '?']


## 4.4 Intro to RegEx

A regular expression (RegEx) is a special sequence of characters that helps you match or find other strings or sets of strings, using a specialized syntax held in a pattern.

re.findall(pattern, string) returns a <u>list</u> containing all matches of pattern in string.

re.split(pattern, string) returns a <u>list</u> where the string has been split at each pattern.

In [28]:
import  re

data = 'Andy-15-A Brad-15-B Cody-16-B'
age_15 = re.findall('15', data)

print(age_15)

stud_info = re.split('\s', data)

print(stud_info)

['15', '15']
['Andy-15-A', 'Brad-15-B', 'Cody-16-B']


Square bracket \[ \] allows to find the match of multiple pattern.

Backslash \ can be inserted before some special characters like ), ], -, or ^ if you want to include them in your pattern.

In [29]:
import re

data = 'Andy-15-A Brad-15-B Cody-16-B'
data_splitted = re.split('[\-\s]', data)

print(data_splitted)

['Andy', '15', 'A', 'Brad', '15', 'B', 'Cody', '16', 'B']


The square bracket \[ \] can also contain a range of characters separated by a hyphen -, in which case it matches any single character within the range. 

\[A-z\] matches any alphabetic character. For upper or lower case only, use \[A-Z\] or \[a-z\].

\[0-9\] matches any digit character.

In [30]:
import re

data = 'Andy-15-A Brad-15-B Cody-16-B'

find_age = re.findall('[0-9][0-9]', data)
find_grade = re.findall('\-[A-Z]', data)

print(find_age)
print(find_grade)

['15', '15', '16']
['-A', '-B', '-B']


To match multiple repetitions of a pattern, you can use the following:

Plus + symbol allows to match zero or more repetitions of the preceding regex.

{m}	matches exactly m repetitions of the preceding regex.

{m,n} matches any number of repetitions of the preceding regex from m to n-1.

In [36]:
import re

data = 'Andy-15-A Brad-15-B Cody-16-B'

find_name = re.findall('[A-z]+\-', data)
find_age_1 = re.findall('\-[0-9]{1}\-', data)
find_age_2 = re.findall('\-[0-9]{2}\-', data)
find_grade = re.findall('\-[A-Z]', data)

print(find_name)
print(find_age_1)
print(find_age_2)
print(find_grade)

['Andy-', 'Brad-', 'Cody-']
[]
['-15-', '-15-', '-16-']
['-A', '-B', '-B']


Parentheses ( ) can be use to group a pattern. It can also be used to return the only necessary part of the pattern to the list.

In [37]:
import re

data = 'Andy-15-A Brad-15-B Cody-16-B'

find_name = re.findall('([A-z]+)\-', data)
find_age = re.findall('\-([0-9]{2})\-', data)
find_grade = re.findall('\-([A-Z])', data)

print(find_name)
print(find_age)
print(find_grade)

['Andy', 'Brad', 'Cody']
['15', '15', '16']
['A', 'B', 'B']


## 4.5 RegEx for Data Cleaning

re.sub(pattern, sub, string) replaces all the pattern in string with sub.

strip() clean unnecessary whitespaces at the start and end of a string.

In [40]:
import re

names = 'Andy;Brad;!Cody'
ages = '15s;1 5;16a'
grades = 'A;#a;B.'

names_clean = re.sub('!', '', names)
ages_clean = re.sub('[A-z\s]', '', ages)
grades_clean = re.sub('[\#\.]', '', grades)

print("Before:")
print(names)
print(ages)
print(grades)

print("\nAfter:")
print(names_clean)
print(ages_clean)
print(grades_clean)

Before:
Andy;Brad;!Cody
15s;1 5;16a
A;#a;B.

After:
Andy;Brad;Cody
15;15;16
A;a;B


In [39]:
import re

raw_info = 'andy;BRAD;!Cody\n15s;1 5;16a\nA;#a;B.'

split_raw_info = re.split('\n',raw_info)

trash = '[\!\#\.\,\s]'
no_trash_info = [re.sub(trash, '', info)
                 for info in split_raw_info]

clean_split = [re.split('\;', info) 
               for info in no_trash_info]

clean_info = clean_split.copy()
clean_info[0] = [info.title() 
                 for info in clean_split[0]]
clean_info[1] = [re.sub('[A-z]', '', info)
                 for info in clean_split[1]]
clean_info[2] = [info.upper()
                 for info in clean_split[2]]

print(f"Raw Data:\n{raw_info}\n")
print(f"Raw Split into List:\n{split_raw_info}\n")
print(f"Cleaned from Symbols:\n{no_trash_info}\n")
print(f"Further Split:\n{clean_split}\n")
print(f"Final Cleaned:\n{clean_info}\n")

Raw Data:
andy;BRAD;!Cody
15s;1 5;16a
A;#a;B.

Raw Split into List:
['andy;BRAD;!Cody', '15s;1 5;16a', 'A;#a;B.']

Cleaned from Symbols:
['andy;BRAD;Cody', '15s;15;16a', 'A;a;B']

Further Split:
[['andy', 'BRAD', 'Cody'], ['15s', '15', '16a'], ['A', 'a', 'B']]

Final Cleaned:
[['Andy', 'Brad', 'Cody'], ['15', '15', '16'], ['A', 'A', 'B']]



In [38]:
names = ['ANdy', "brad;", "cody", "drew "]
marks_1 = ['65', ' 75',  '65s', ' 80']
marks_2 = ['65 ', '8 5',  '66?', '!60']

import re

def clean_strings(strings):
  result = []
  for value in strings:
    value = value.strip()
    value = re.sub('[-!#?;\s]', '', value)
    value = value.title()
    result.append(value)
  return result

print(f"Name: {clean_strings(names)}")
print(f"Marks 1: {clean_strings(marks_1)}")
print(f"Marks 2: {clean_strings(marks_2)}")

Name: ['Andy', 'Brad', 'Cody', 'Drew']
Marks 1: ['65', '75', '65S', '80']
Marks 2: ['65', '85', '66', '60']


## 5.1 Numpy Arrays

np.array() converts a list/tuples into an ndarray.

array.ndim returns the dimension of array:
- 0-D array: A number/scalar
- 1-D array: a list with numbers.
- 2-D array: a list containing lists, a matrix.

array.shape returns the shape of an array.

In [1]:
import numpy as np

marks  = [60, 65, 70]
mark_arr = np.array(marks)

print(mark_arr)
print(type(mark_arr))

mark = np.array(60) 
mark_list = np.array([60, 85, 70])
mark_lists  = np.array([[60, 85, 70],
                        [65, 65, 60]])

arrays = [mark, mark_list, mark_lists]
for arr in arrays:
  print(arr)

[60 65 70]
<class 'numpy.ndarray'>
60
[60 85 70]
[[60 85 70]
 [65 65 60]]


Similar to range, NumPy has some functions that make it easy to generate numbers:

- np.arange(num) returns integers from 0 to num-1. 

- np.arange(minnum, maxnum) returns integers from minnum to maxnum-1. 

- np.full(shape, fill_value) returns a new array of the given shape (e.g., (2,3) or 2) filled with fill_value.

- np.empty(shape) returns a new array of the given shape with no value in it.

You can use round(num) to round a number to num places decimal.

In [3]:
import numpy as np

stud_id = np.arange(1, 7)
grade_pass = np.full((2,6), 65)
stud_grade = np.empty((2,6))

print(stud_id)
print(grade_pass)
print(stud_grade.round(1))

[1 2 3 4 5 6]
[[65 65 65 65 65 65]
 [65 65 65 65 65 65]]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


NumPy offers the random module to work with random numbers.  

- np.random.rand() returns random float from 0 to 1.

- np.random.randint(num) returns random integers from 0 to num-1.

- np.random.randint(minnum, maxnum) returns random integers from minnum to maxnum-1. 

Adding an extra argument size=shape will return a random array of the given shape.

In [1]:
import numpy as np

random_num = np.random.rand(2,5).round(2)
random_mark = np.random.randint(50, 101, size=(2,5))

print(random_num)
print(random_mark)

[[0.73 0.35 0.9  0.03 1.  ]
 [0.28 0.31 0.67 0.89 0.56]]
[[69 95 56 72 54]
 [77 75 84 69 52]]


## 5.2 Index and Reshape

You can access an array element by referring to its index number just like in list with similar methods with 2 or 3 Ds arrays.

In [4]:
import numpy as np

marks_arr = np.array([60, 75, 80, 85, 70, 60])
marks_arr_2D = np.array([[60, 75, 80], [85, 70, 60]])

print(marks_arr[0])
print(marks_arr_2D[1,1])

60
70


We pass slice like this \[start:end\] or \[start:end:step\]

In [5]:
import numpy as np

marks_arr = np.array([60, 75, 80, 85, 70, 60])
marks_arr_2D = np.array([[60, 75, 80], [85, 70, 60]])

print(marks_arr[2:5])
print(marks_arr_2D[1:,1:])

[80 85 70]
[[70 60]]


array.reshape(shape) returns an array of new shape from array.

In [6]:
import numpy as np

marks_arr = np.array([60, 75, 80, 85, 70, 60])
marks_arr_2D = marks_arr.reshape(2,3)

print(marks_arr)
print(marks_arr_2D)

[60 75 80 85 70 60]
[[60 75 80]
 [85 70 60]]


Pass -1 as the value, and NumPy will calculate this number for you. But you have to be aware of whether the whole items can be devided into the shape you want.

Reshaping using (-1,1) value is particularly useful to convert a row array into a column array and vice versa.

In [7]:
import numpy as np

marks_arr = np.array([60, 75, 80, 85, 70, 60])
marks_arr_2D = marks_arr.reshape(3,-1)
marks_arr_col = marks_arr.reshape(-1,1)

print(marks_arr)
print(marks_arr_2D)
print(marks_arr_col)

[60 75 80 85 70 60]
[[60 75]
 [80 85]
 [70 60]]
[[60]
 [75]
 [80]
 [85]
 [70]
 [60]]


## 5.3 Unviersal Function

Universal functions (or ufunc) are NumPy functions that operate on the ndarray object. Many ufunc are related to mathematical operations between arrays.
- add()
- subtract()
- multiply()
- divide()
- power() 

In [9]:
import numpy as np

marks_1_arr = np.array([60, 75, 80, 85, 70, 60])
marks_2_arr = np.array([65, 70, 80, 75, 90, 65])

marks_sum = np.add(marks_1_arr, marks_2_arr)
marks_ave = np.divide(marks_sum, 10)
marks_sub = np.subtract(marks_1_arr, marks_2_arr)
print(marks_sum)
print(marks_ave)
print(marks_sub)

[125 145 160 160 160 125]
[12.5 14.5 16.  16.  16.  12.5]
[ -5   5   0  10 -20  -5]


Also you can use functions as follows to computing basic statistical indexes with numpy. 
- amin(ar),  amax(ar) return the minimum, maximum of an array, respectively.
- sum(ar) computes the sum of all elements.
- mean(ar) computes the arithmetic mean.
- median(ar) computes the median.
- std(ar) computes the standard deviation.
- quantile(ar,q) computes the q-th quantile of the data.

And for 2-D array, you can add an extra argument:
- axis=0 to compute the rows statistics
- axis=1 to compute the columns statistics

In [10]:
import numpy as np

marks_arr = np.array([(60, 75, 80, 85, 70),
                      (65, 70, 80, 75, 90)])

marks_sum = np.sum(marks_arr, axis=0)
marks_ave = np.mean(marks_arr, axis=0)
marks_std = np.std(marks_arr, axis=0)
marks_min = np.amin(marks_arr, axis=1)
marks_max = np.amax(marks_arr, axis=1)


print(f'Sum: {marks_sum}')
print(f'Ave: {marks_ave}')
print(f'Std: {marks_std}')
print(f'Row 1 Min: {marks_min[0]}')
print(f'Row 1 Max: {marks_max[0]}')
print(f'Row 2 Min: {marks_min[1]}')
print(f'Row 2 Max: {marks_max[1]}')

Sum: [125 145 160 160 160]
Ave: [62.5 72.5 80.  80.  80. ]
Std: [ 2.5  2.5  0.   5.  10. ]
Row 1 Min: 60
Row 1 Max: 85
Row 2 Min: 65
Row 2 Max: 90


Also we can apply trigonometric and logarithmic operators.
- e, pi return the value of Euler's constant and pi, respectively.
- sin(), cos() and tan() take values in radians and produce the corresponding sin, cos and tan values.
- sinh(), cosh() and tanh() take values in radians and produce the corresponding sinh, cosh and tanh values.
- log(), log10() function to perform corresponding log at the base e and 10.

In [11]:
import numpy as np

q1 = np.sin(0.5*np.pi)
q2 = np.sinh(np.log(2))
q3 = np.cos(np.pi)
q4 = np.log10(0.01)
q5 = np.log(np.e**5)

print(f' sin(0.5pi) = {q1:.1f}')
print(f'sinh(ln(2)) = {q2:.3f}')
print(f'    cos(pi) = {q3:.0f}')
print(f'log10(0.01) = {q4:.0f}')
print(f'    ln(e^5) = {q5:.1f}')
#remind here ':.xf'

 sin(0.5pi) = 1.0
sinh(ln(2)) = 0.750
    cos(pi) = -1
log10(0.01) = -2
    ln(e^5) = 5.0


To apply set operators.

- unique() returns the unique elements from any array, e.g., create a set array. (should only be 1-D)
- union1d(ar1, ar2) finds the union of ar1 and ar2.
- intersect1d(ar1, ar2) finds the intersection of ar1 and ar2.
- setdiff1d(ar1, ar2) find the set difference of ar1 and ar2.
- isin(ar1, ar2) test whether each element of ar1 is also present in ar2.

(Note that Python set cannot be converted to ndarray)

In [16]:
import numpy as np

class_S = np.array(['math', 'english', 'history'])
class_F = np.array(['math', 'science', 'economy'])

class_unique = np.unique(class_S)
class_taken = np.union1d(class_S, class_F)
class_repeated = np.intersect1d(class_S, class_F)
class_no_repeat = np.setdiff1d(class_S, class_F)
class_check = np.isin(class_S, class_F)

print(f'Unique Class in Summer:\n{class_unique}\n')
print(f'Classes Taken:\n{class_taken}\n')
print(f'Classes Repeated:\n{class_repeated}\n')
print(f'Class_S Not Repeated:\n{class_no_repeat}\n')
print(f'Is Class Repeated in Fall?:\n{class_check}')

Unique Class in Summer:
['english' 'history' 'math']

Classes Taken:
['economy' 'english' 'history' 'math' 'science']

Classes Repeated:
['math']

Class_S Not Repeated:
['english' 'history']

Is Class Repeated in Fall?:
[ True False False]


## 5.4 Join, Split and Transpose

np.concatenate((arr1, arr2, ...)) joins arr1, arr2, ..., along with the axis. If axis is not explicitly passed, it is taken as 0.

In [20]:
import numpy as np

marks_1 = np.array([60, 75, 80, 85, 70, 60])
marks_2 = np.array([65, 70, 80, 75, 90, 65])

marks_all = np.concatenate((marks_1, marks_2))

print(marks_all)

[60 75 80 85 70 60 65 70 80 75 90 65]


np.array_split(arr, num) splits arr into num sub-arrays. It will return a list object (not ndarray).

In [23]:
import numpy as np

marks_1 = np.array([60, 75, 80, 85, 70, 60])
marks_2 = np.array([65, 70, 80, 75, 90, 65])

marks_all = np.concatenate((marks_1, marks_2))

marks_split_4 = np.array_split(marks_all, 4)

print(f'Split into 4 parts:')
print(marks_split_4)
print(type(marks_split_4))

Split into 4 parts:
[array([60, 75, 80]), array([85, 70, 60]), array([65, 70, 80]), array([75, 90, 65])]
<class 'list'>


We can concatenate two 1-D arrays along the second axis which would result in putting them one over the other, ie. stacking.

- np.vstack(\[arr1, arr2, ...\]) stack arr1, arr2, ..., in sequence vertically (row wise).

- np.hstack(\[arr1, arr2, ...\]) stack arr1, arr2, ..., in sequence horizontally (column wise).

In [26]:
import numpy as np

marks_12 = np.array([[60, 75, 80, 85, 70, 60],
                     [65, 70, 80, 75, 90, 65]])
marks_3  = np.array( [70, 85, 75, 85, 90, 80] )

marks_123 = np.vstack([marks_12, marks_3])

marks_final = np.array([[70],
                        [75],
                        [85]])
                        
marks = np.hstack([marks_123, marks_final])
#be careful on the order of two arrs
mark_rev = np.hstack([marks_final, marks_123])

print(marks_12,'\n')
print(marks_123,'\n')
print(marks,'\n')
print(mark_rev)

[[60 75 80 85 70 60]
 [65 70 80 75 90 65]] 

[[60 75 80 85 70 60]
 [65 70 80 75 90 65]
 [70 85 75 85 90 80]] 

[[60 75 80 85 70 60 70]
 [65 70 80 75 90 65 75]
 [70 85 75 85 90 80 85]] 

[[70 60 75 80 85 70 60]
 [75 65 70 80 75 90 65]
 [85 70 85 75 85 90 80]]


np.transpose(arr) reverses the axes of arr and returns the modified array.

In [27]:
import numpy as np

names = np.array(['Andy','Brad','Cody','Drew'])
marks_1 = np.array([60, 75, 80, 85])
marks_2 = np.array([65, 70, 80, 75])

marks_stack = np.vstack([names, marks_1, marks_2])
marks_swaps = np.transpose(marks_stack)

print(marks_stack, '\n')
print(marks_swaps)

[['Andy' 'Brad' 'Cody' 'Drew']
 ['60' '75' '80' '85']
 ['65' '70' '80' '75']] 

[['Andy' '60' '65']
 ['Brad' '75' '70']
 ['Cody' '80' '80']
 ['Drew' '85' '75']]


## 5.5 Search and Filter

In NumPy, you filter an array using a boolean index list  An element is contained in the filtered array only if the value at an index is True. Use bitwise operator &, |, ~ for and, or, and not, respectively.

In [28]:
import numpy as np

marks = np.array([65, 67, 70, 60, 50])

filter_bool = (marks > 65) & (marks <= 100)
#here we create a boolean index and it will be used in next filter
pass_array = marks[filter_bool]
print(pass_array)

fail_array = marks[~filter_bool]
#here use the boolean operator ~ to do the logicall calculation
print(fail_array)

[67 70]
[65 60 50]


Using a list comprehension with if statement can be useful for filtering.   
<b>While there is no ndarray comprehension</b>, a similar task can be done using this method:

where(condition, x, y) returns elements chosen from x or y depending on condition.

In [30]:
import numpy as np

names = ["Andy", "Brad", "Cody"]
marks_1 = [60, 85, 70]
marks_2 = [65, 65, 60]

marks_arr = np.array([marks_1, marks_2])

marks_ave = np.mean(marks_arr, axis=0)
results = np.where(marks_ave > 65, 'Pass', 'Fail') 
#here it returns a list from where

names_results = list(zip(names, results))
print(names_results)

[('Andy', 'Fail'), ('Brad', 'Pass'), ('Cody', 'Fail')]


Unlike list, NumPy can only work with 1 data type. We can force NumPy to work with multiple data types by assigning a dtype. The resulting array is called a structured array. 

In [31]:
import numpy as np

stud_info = [('Andy', 60),
             ('Brad', 85),
             ('Cody', 70),
             ('Drew', 75)]

dtypes = [('name',object), ('mark',int)]
#define the types while using numpy
stud_marks = np.array(stud_info, dtype=dtypes)

print(stud_marks)

[('Andy', 60) ('Brad', 85) ('Cody', 70) ('Drew', 75)]


Use the function as follows to sort ndarray.

np.sort(arr)returns a sorted copy of an array.

In [32]:
import numpy as np

stud_info = [('Andy', 60),
             ('Brad', 85),
             ('Cody', 70),
             ('Drew', 75)]

dtypes = [('name',object), ('mark',int)]

stud_marks = np.array(stud_info, dtype=dtypes)

sorted_marks = np.sort(stud_marks, order='mark') 

print(stud_marks)
print(sorted_marks)

[('Andy', 60) ('Brad', 85) ('Cody', 70) ('Drew', 75)]
[('Andy', 60) ('Cody', 70) ('Drew', 75) ('Brad', 85)]
